/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://syv23mxrdfaqvlzjfhltaiuyny.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jvadj32sdnavlgfrfgm56yuomi",
    "aws_cognito_identity_pool_id": "ap-south-1:d237fd96-5cd5-4e69-b3b8-ba96e5333f91",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_6eZvw0VrV",
    "aws_user_pools_web_client_id": "2quugk1s6j2d14mbs00ec7p1vn",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
